### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by HasanliHilal** [mapbox/store-locator-react-native#14]
my program using store-locator-react-native.But zoom not working.Change zoom when open the map.I checked the map without featured zoom working.This problem have in android.How to fixed?

**Comment by goodryanboy** [comment]
> my program using store-locator-react-native.But zoom not working.Change zoom when open the map.I checked the map without featured zoom working.This problem have in android.How to fixed?

how did you solve this?

**Comment by nendrawono** [comment]
How solve this problem ?
